image:
  repository: "ghcr.io/eschercloudai/baski-ui"
  pullPolicy: Always
  tag: "0.0.0"

imagePullSecrets:
  - name: ghcr

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: baski-ui-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  hosts:
    - host: baski-ui.eckmgt.nl1.eschercloud.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: baski-ui-tls
      hosts:
        - baski-ui.eckmgt.nl1.eschercloud.dev

baskiServer:
  endpoint: "http://baski-server.baski-server.svc"
