apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "baski-ui.fullname" . }}
  labels:
    {{- include "baski-ui.labels" . | nindent 4 }}
data:
  env: |
    PUBLIC_API_URL={{ .Values.baskiServer.endpoint }}
