apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "baski-ui.serviceAccountName" . }}
  labels:
    {{- include "baski-ui.labels" . | nindent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{ .Values.imagePullSecrets | toYaml | indent 2 }}
{{- end }}
