apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "baski-ui.serviceAccountName" . }}
  labels:
    {{- include "baski-ui.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
{{ . }}
{{- end }}
